Repository alx3416/Tallergit, pull requests merged in 2023-11, with the labels that each got.

#5 Add getAreaTriangle function
  myLibrary.py
Labels: enhancement

#11 Create funcion cilindro.py
  funcion cilindro.py
Labels: good first issue

#10 get volume for a sphere
  myLibrary.py
Labels: bug

#12 area cilindro
  myLibrary.py
Labels: enhancement
